# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Common data types and DTOs for the Tunix Orchestrator and Workers.

This module centralizes type aliases and dataclasses used for:
1) Routing data and commands between Orchestrator and workers.
2) Defining common data structures used by Orchestrator and workers.
"""

import dataclasses
from typing import Any

from jax.typing import ArrayLike  # pylint: disable=g-importing-member
import numpy as np
from tunix.rl.agentic.agents import agent_types

##### Worker-internal datatypes #####

# Worker-internal episode representation produced during rollout.
Trajectory = agent_types.Trajectory
Step = agent_types.Step
TrajectoryStatus = agent_types.TrajectoryStatus


##### Common DTOs (Data Transfer Objects) #####


@dataclasses.dataclass(kw_only=True)
class ErrorInfo:
  """Structured description of a failed request, carried in-band on a result.

  Attributes:
    error_type: Short classifier for the failure (e.g. an exception class name).
    message: Human-readable failure description.
    retryable: Whether re-issuing the request could plausibly succeed.
    traceback: Optional captured traceback, for diagnostics.
  """

  error_type: str
  message: str
  retryable: bool = False
  traceback: str = ""


@dataclasses.dataclass(kw_only=True)
class Request:
  """Standard base for generic RPC requests.

  Attributes:
    request_id: Unique identifier for this request, echoed back on the
      corresponding response so callers can correlate responses.
    metadata: Optional free-form data attached to the request.
  """

  request_id: str = ""
  metadata: dict[str, Any] = dataclasses.field(default_factory=dict)


@dataclasses.dataclass(kw_only=True)
class Response:
  """Standard response for generic RPC requests.

  Attributes:
    request_id: Echoes the originating request_id for correlation.
    error: Structured failure details when the operation failed, else None.
    metadata: Optional free-form data attached to the response.
  """

  request_id: str = ""
  error: ErrorInfo | None = None
  metadata: dict[str, Any] = dataclasses.field(default_factory=dict)


@dataclasses.dataclass(kw_only=True)
class SamplingParams:
  """Engine-neutral sampling configuration for a generation request.

  Attributes:
    max_tokens: Maximum number of tokens to generate.
    temperature: Softmax temperature applied while sampling. Kept explicit so it
      can be carried through to any later log-probability scoring, ensuring the
      sampling distribution and the scoring distribution match.
  """

  max_tokens: int
  temperature: float = 1.0


@dataclasses.dataclass(kw_only=True)
class SamplingRequest(Request):
  """Request to generate completions for a single prompt from a Sampler.

  Attributes:
    prompt: The source prompt to sample from (formatted string, token array, or
      chat dictionary).
    sampling_params: Optional per-request sampling configuration.
  """

  prompt: Any
  sampling_params: SamplingParams | None = None


@dataclasses.dataclass(kw_only=True)
class SamplingResponse(Response):
  """Serializable result of a single sampling/completion request from a Sampler.

  Attributes:
    text: Detokenized completion text string generated by the model.
    token_ids: Array of generated token IDs (unpadded).
    logprobs: Array of per-token log-probabilities under the sampling policy
      (required for RL), or None if not requested.
    finish_reason: Reason generation terminated (e.g., "stop", "length",
      "cancelled", "error").
    error: Structured failure details when sampling failed for this prompt, else
      None.
  """

  text: str = ""
  token_ids: np.ndarray = dataclasses.field(
      default_factory=lambda: np.zeros(0, dtype=np.int32)
  )
  logprobs: np.ndarray | None = None
  finish_reason: str = "stop"

  def __post_init__(self):
    if (
        self.logprobs is not None
        and self.logprobs.shape != self.token_ids.shape
    ):
      raise ValueError(
          f"logprobs shape {self.logprobs.shape} != token_ids shape"
          f" {self.token_ids.shape}"
      )


@dataclasses.dataclass(kw_only=True)
class WeightSyncRequest(Request):
  """Configuration and routing metadata for synchronizing policy model weights.

  Attributes:
    controller_id: Optional identifier for transport controllers (e.g., TPU
      Raiden).
    policy_version: Target policy version identifier of the weights to sync.
    source_metadata: Optional transport/layout metadata describing source
      weights.
    extra_config: Optional backend-specific configuration parameters.
  """

  controller_id: str = ""
  policy_version: int = 0
  source_metadata: Any = None
  extra_config: dict[str, Any] = dataclasses.field(default_factory=dict)


@dataclasses.dataclass(kw_only=True)
class RolloutRequest(Request):
  """Request to generate a rollout from a given prompt.

  Attributes:
    prompt: The prompt to generate from (e.g. formatted string, token array, or
      chat dictionary).
    prompt_id: Unique identifier for this prompt within a task or dataset.
    group_id: Optional identifier for grouping related rollout requests (e.g.
      for GRPO).
    generation_kwargs: Additional keyword arguments for generation (e.g.
      sampling parameters like max_tokens and temperature).
    sampling_params: Optional structured sampling configuration. The typed
      alternative to `generation_kwargs`, used when the caller wants the
      sampling distribution pinned (so later scoring can match it).
    max_turns: Maximum number of conversation turns for environment interaction.
    target_policy_version: Policy model version identifier to use for rollout
      generation.
  """

  prompt: Any = ""
  prompt_id: str = "default_prompt"
  group_id: str = ""
  generation_kwargs: dict[str, Any] = dataclasses.field(default_factory=dict)
  sampling_params: "SamplingParams | None" = None
  max_turns: int = 10
  target_policy_version: int = 0


@dataclasses.dataclass(kw_only=True)
class TokenSegment:
  """One contiguous span of the conversation token stream representing a single turn.

  Each segment corresponds to a single turn's response from either the assistant
  or the environment.

  Attributes:
    source: Origin of the span, e.g. "assistant" (model-emitted) or "env".
    tokens: Array of token ids for this span.
    loss_mask: Array of ints, 1 where the token is model-emitted (trainable).
    logps: Array of per-token log-probabilities under the sampling
      distribution, or None for spans the model did not emit (e.g. env tokens).
  """

  source: str
  tokens: np.ndarray
  loss_mask: np.ndarray
  logps: np.ndarray | None = None

  def __post_init__(self):
    if self.loss_mask.shape != self.tokens.shape:
      raise ValueError(
          f"loss_mask shape {self.loss_mask.shape} != tokens shape"
          f" {self.tokens.shape}"
      )
    if self.logps is not None and self.logps.shape != self.tokens.shape:
      raise ValueError(
          f"logps shape {self.logps.shape} != tokens shape"
          f" {self.tokens.shape}"
      )


@dataclasses.dataclass(kw_only=True)
class RolloutResponse(Response):
  """Serializable result of a generation request.

  This is the wire-facing counterpart to RolloutRequest (and to the
  worker-internal Trajectory): it carries only primitives and numpy
  arrays, so it can cross a process boundary. A failed request is reported as a
  result with `error` set and a non-success `status`, never as a dropped
  response.

  Attributes:
    status: Terminal status name (e.g. a rollout trajectory status, or
      "CANCELLED").
    prompt_id: Echoes the source prompt id, so responses can be grouped back to
      the prompt they came from.
    prompt_tokens: Array of prompt token ids, unpadded, as tokenized by the
      worker.
    segments: Ordered conversation turns (segments) from the assistant (model
      call) and environment; concatenated they form the full generated stream.
    env_reward: Scalar environment reward for the trajectory.
    policy_version: Weight version used to generate the trajectory.
    error: Failure details when the request did not succeed, else None.
  """

  status: str
  prompt_id: str = ""
  prompt_tokens: np.ndarray = dataclasses.field(
      default_factory=lambda: np.zeros(0, dtype=np.int32)
  )
  segments: list[TokenSegment] = dataclasses.field(default_factory=list)
  env_reward: float = 0.0
  policy_version: int = 0
  # TODO(b/532722981): capture rollout metrics, e.g., env time.

  @classmethod
  def from_trajectory(
      cls,
      request_id: str,
      traj: Trajectory,
      prompt_tokens: np.ndarray,
      policy_version: int,
  ) -> "RolloutResponse":
    """Constructs a wire-safe RolloutResponse from an internal Trajectory.

    Extracts only the required arrays (tokens, masks, logprobs) from the
    semantic steps, discarding string metadata and unpicklable objects.

    Args:
      request_id: The ID of the original rollout request.
      traj: The internal trajectory to convert.
      prompt_tokens: Array of prompt token ids.
      policy_version: Weight version used to generate the trajectory.

    Returns:
      A wire-safe RolloutResponse.
    """
    segments = []
    for step in traj.steps:
      if step.assistant_tokens is not None:
        segments.append(
            TokenSegment(
                source="assistant",
                tokens=step.assistant_tokens,
                loss_mask=step.assistant_masks,
                logps=step.logprobs,
            )
        )
      if step.env_tokens is not None:
        segments.append(
            TokenSegment(
                source="env",
                tokens=step.env_tokens,
                loss_mask=step.env_masks,
                logps=None,
            )
        )
    return cls(
        request_id=request_id,
        status=traj.status.name,
        prompt_tokens=prompt_tokens,
        segments=segments,
        env_reward=traj.reward,
        policy_version=policy_version,
    )


@dataclasses.dataclass(kw_only=True)
class TrainerPayload:
  """Generic trainer payload.

  Attributes:
    token_ids: [B, T] token IDs. By default, structured as left-padded prompt
      tokens concatenated with right-padded completion tokens.
    token_mask: [B, T] token mask to differentiate padding tokens from valid
      tokens.
    segment_ids: Optional [B, T] packing segment ids.
  """

  token_ids: ArrayLike
  token_mask: ArrayLike
  segment_ids: ArrayLike | None = None


@dataclasses.dataclass(kw_only=True)
class RLTrainerPayload(TrainerPayload):
  """RL training payload.

  Attributes:
    advantages: [B] or [B, C] advantages.
    loss_mask: [B, T], 1 where the position contributes to the loss.
    ref_per_token_logps: Optional [B, C] reference model log-probabilities.
    old_per_token_logps: Optional [B, C] behavior policy log-probabilities.
    sampler_is_weights: Optional [B, C] importance sampling weights.
  """

  advantages: ArrayLike
  loss_mask: ArrayLike
  ref_per_token_logps: ArrayLike | None = None
  old_per_token_logps: ArrayLike | None = None
  sampler_is_weights: ArrayLike | None = None


@dataclasses.dataclass(kw_only=True)
class LogprobsRequest(Request):
  """Request to score per-token log-probabilities under a frozen model.

  Attributes:
    prompt_tokens: [B, P], LEFT-padded.
    completion_tokens: [B, C], RIGHT-padded; the result aligns to these
      completion columns.
    temperature: Softmax temperature to score under. Mandatory: it must match
      the temperature the tokens were sampled at, or the log-probs are biased.
    model_role: Which hosted model to score against (v1: "reference").
  """

  prompt_tokens: np.ndarray
  completion_tokens: np.ndarray
  temperature: float
  model_role: str = "reference"


@dataclasses.dataclass(kw_only=True)
class LogprobsResponse(Response):
  """Per-token log-probabilities for a LogprobsRequest.

  Attributes:
    per_token_logps: [B, C], aligned to the request's completion columns.
    model_version: Version of the scoring weights (constant for a frozen model).
    error: Failure details when the request did not succeed, else None.
  """

  per_token_logps: np.ndarray
  model_version: int = 0


@dataclasses.dataclass(kw_only=True)
class ScoreRequest(Request):
  """Request to score scalar rewards/values under a hosted model.

  Attributes:
    prompt_tokens: [B, P], LEFT-padded.
    completion_tokens: [B, C], RIGHT-padded.
    model_role: Which hosted model to score against (e.g. "reward").
  """

  prompt_tokens: np.ndarray
  completion_tokens: np.ndarray
  model_role: str = "reward"


@dataclasses.dataclass(kw_only=True)
class ScoreResponse(Response):
  """Scalar scores for a ScoreRequest.

  Attributes:
    scores: [B], one scalar per row.
    model_version: Version of the scoring weights (constant for a frozen model).
    error: Failure details when the request did not succeed, else None.
  """

  scores: np.ndarray
  model_version: int = 0


##### Trainer step DTOs #####


@dataclasses.dataclass(kw_only=True)
class StepReceipt:
  """Result of one fwd_bwd (gradient-accumulation) micro-step.

  Attributes:
    accum_id: Identifies the accumulation group this micro-step belongs to.
    micro_index: Position of this micro-batch within its accumulation group.
    applied: Whether an optimizer update was applied. False for fwd_bwd, which
      only accumulates gradients.
    micro_loss: The normalized loss for this micro-batch.
    denominator: The normalization denominator for this micro-batch (e.g. token
      or sequence count) so the caller can rescale and accumulate correctly.
  """

  accum_id: str
  micro_index: int
  applied: bool = False
  micro_loss: float = 0.0
  denominator: float = 0.0


@dataclasses.dataclass(kw_only=True)
class UpdateResult:
  """Result of applying accumulated gradients as one optimizer update.

  Attributes:
    step: The optimizer step count after this update.
    applied: Whether the update was applied (False for a no-op / duplicate).
    grad_norm: Global gradient norm for the update, when computed.
  """

  step: int
  applied: bool = True
  grad_norm: float | None = None


##### Worker lifecycle DTOs #####


@dataclasses.dataclass(kw_only=True)
class ShapeConfig:
  """Shape hints a worker uses to synthesize its own warmup dummies for compile().

  Attributes:
    max_prompt_length: Maximum (left-padded) prompt length.
    max_response_tokens: Maximum completion length.
    micro_batch_sizes: Micro-batch sizes to warm up (compile) for.
  """

  max_prompt_length: int
  max_response_tokens: int
  micro_batch_sizes: list[int] = dataclasses.field(default_factory=list)


@dataclasses.dataclass(kw_only=True)
class TokenizerInfo:
  """Tokenizer identity a worker reports so scoring/assembly stays consistent.

  Attributes:
    pad_id: Padding token id.
    eos_id: End-of-sequence token id.
    tokenizer_hash: Optional stable hash of the tokenizer; startup validation
      checks that every worker reports the same one.
  """

  pad_id: int
  eos_id: int
  tokenizer_hash: str | None = None


@dataclasses.dataclass(kw_only=True)
class HealthReport:
  """Liveness/status snapshot a worker reports to the orchestrator.

  Attributes:
    state: Coarse worker state, e.g. "READY", "COMPILING", "BUSY", "DRAINING",
      "SYNCING", "STOPPED".
    inflight: Number of in-flight units of work.
    queue_depth: Depth of the worker's internal work queue.
    policy_version: Installed weight/policy version.
    last_error: Most recent error string, if any.
    heartbeat_unix_s: Unix timestamp of this report.
  """

  state: str
  inflight: int = 0
  queue_depth: int = 0
  policy_version: int = 0
  last_error: str | None = None
  heartbeat_unix_s: float = 0.0


@dataclasses.dataclass(kw_only=True)
class WorkerInfo:
  """Static description of a worker, for registration and scheduling.

  Attributes:
    worker_id: Unique id of the worker.
    roles: Logical roles this worker serves (e.g. {"trainer", "inference"}); a
      fused worker joins every matching group.
    capabilities: Declared capability flags (e.g. "segment_attention").
    placement_group: Colocation group id, or None if not colocated.
    resources: Resource/topology description (e.g. process_count, mesh, hbm_gb).
  """

  worker_id: str
  roles: frozenset[str] = frozenset()
  capabilities: frozenset[str] = frozenset()
  placement_group: str | None = None
  resources: dict[str, Any] = dataclasses.field(default_factory=dict)


##### Weight-sync transport DTOs #####
# Distinct from the `WeightSyncRequest` wire DTO above: these describe the
# staging/fetch handshake between the trainer and the replicas.


@dataclasses.dataclass(kw_only=True)
class WeightSyncSpec:
  """Orchestrator -> trainer: what to stage for a weight sync.

  Attributes:
    version: Weight version being staged (assigned by the orchestrator).
    method: Transport method, e.g. "in_process", "checkpoint", "p2p".
    param_filter: Which params to stage, "full" or "lora".
  """

  version: int
  method: str = "in_process"
  param_filter: str = "full"


@dataclasses.dataclass(kw_only=True)
class WeightSyncMetadata:
  """Trainer -> replicas: how to fetch staged weights.

  Attributes:
    version: Weight version being fetched (echoes the spec).
    method: Transport method used to stage.
    locator: How to reach the weights (checkpoint path, (address, uuid), or a
      live in-process handle). This is the one wire carve-out that may hold a
      non-serializable handle, and only under the in-process transport.
  """

  version: int
  method: str
  locator: Any = None


@dataclasses.dataclass(kw_only=True)
class TrainExampleV1:
  """RL training example with a split prompt/completion layout (numpy wire).

  The numpy wire twin of the on-device agentic `TrainExample`. It is kept
  separate from `RLTrainerPayload`, which carries a single concatenated
  `token_ids`/`token_mask` pair: this one keeps prompts and completions in
  distinct arrays, which is what the group assembler produces and what the
  agentic postprocess consumes.

  Attributes:
    loss_mask: int32 [B, C], 1 where the position contributes to the loss.
    prompt_ids: int32 [B, P] left-padded prompt tokens.
    prompt_mask: int32 [B, P] prompt mask.
    completion_ids: int32 [B, C] right-padded completion tokens.
    advantages: float32 [B] or [B, C] advantages.
    schema_version: DTO schema version (evolution is additive).
    segment_ids: Optional int32 [B, T] packing segment ids.
    segment_positions: Optional int32 [B, T] within-segment positions.
    old_per_token_logps: float32 [B, C] sampler/old-policy logps, or None.
    ref_per_token_logps: float32 [B, C] reference-policy logps, or None
      (injected by the inference stage when beta != 0).
    policy_version: int32 [B] per-row weight version used at generation.
  """

  loss_mask: np.ndarray
  prompt_ids: np.ndarray
  prompt_mask: np.ndarray
  completion_ids: np.ndarray
  advantages: np.ndarray
  schema_version: int = 1
  segment_ids: np.ndarray | None = None
  segment_positions: np.ndarray | None = None
  old_per_token_logps: np.ndarray | None = None
  ref_per_token_logps: np.ndarray | None = None
  policy_version: np.ndarray | None = None
