#!/usr/bin/env python3
"""Render the three immutable V1 high-performance full-training JobSets."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import sys

import yaml


_TASK_DIR = Path(__file__).resolve().parents[1]
_PACKAGE_ROOT = _TASK_DIR.parents[1]
_REPO_ROOT = _PACKAGE_ROOT.parent
_CLUSTER_DIR = _PACKAGE_ROOT / "cluster"
for path in (_REPO_ROOT, _CLUSTER_DIR):
  if str(path) not in sys.path:
    sys.path.insert(0, str(path))

import render_p33_jobsets as p33
import render_p57_frozenlake_tim as p57


_SHA_RE = re.compile(r"[0-9a-f]{40}")
_GSM8K_PROFILE = (
    "cluster/profiles/qwen3-1p7b-dp16-tp4-gsm8k-v1-hp.env"
)
_JAX_CACHE_ENV = {
    "JAX_COMPILATION_CACHE_DIR": "/tmp/jax_compilation_cache",
    "JAX_PERSISTENT_CACHE_MIN_COMPILE_TIME_SECS": "0",
    "JAX_PERSISTENT_CACHE_ENABLE_XLA_CACHES": "all",
    "CANON_GCS_CACHE_BUCKET": (
        "gs://yuxzhang-tunix-models/cache/p33_compilation_cache"
    ),
}


def _container(document: dict) -> dict:
  pod = document["spec"]["replicatedJobs"][0]["template"]["spec"][
      "template"
  ]["spec"]
  return next(item for item in pod["containers"] if item["name"] == "jax-tpu")


def _env(document: dict) -> dict[str, str]:
  return {
      item["name"]: item["value"]
      for item in _container(document)["env"]
      if "value" in item
  }


def _set_env(document: dict, values: dict[str, str]) -> None:
  entries = _container(document)["env"]
  existing = {entry["name"] for entry in entries}
  overlap = existing & values.keys()
  if overlap:
    raise ValueError(f"refusing to overwrite rendered env: {sorted(overlap)}")
  entries.extend(
      {"name": name, "value": value} for name, value in values.items()
  )


def _sha256(path: Path) -> str:
  digest = hashlib.sha256()
  with path.open("rb") as source:
    for chunk in iter(lambda: source.read(1024 * 1024), b""):
      digest.update(chunk)
  return digest.hexdigest()


def _write_yaml(path: Path, document: dict) -> None:
  header = (
      "# Generated by v1-phase4 render_three_full_recipes.py.\n"
      "# Do not edit; change the reviewed renderer/profile.\n"
  )
  path.write_text(
      header + yaml.safe_dump(document, sort_keys=False), encoding="utf-8"
  )


def render_three(
    *,
    source_commit: str,
    output_dir: Path,
    gsm8k_run_id: str,
    p45_run_id: str,
    m15_run_id: str,
    campaign_root: str,
    base_path: Path,
) -> tuple[Path, ...]:
  if not _SHA_RE.fullmatch(source_commit):
    raise ValueError("source commit must be exactly 40 lowercase hex characters")
  if output_dir.exists():
    raise FileExistsError(f"refusing to overwrite output root: {output_dir}")
  if len({gsm8k_run_id, p45_run_id, m15_run_id}) != 3:
    raise ValueError("all three run ids must be distinct")

  output_dir.mkdir(parents=True)
  gsm_dir = output_dir / "gsm8k"
  gsm_dir.mkdir()
  base = p33.load_base(base_path)
  gsm_spec = p33.JobSpec(
      key="gsm8k-v1-hp-full",
      workload="gsm8k",
      stage="full",
      profile=_GSM8K_PROFILE,
      no_commit=False,
      job_prefix="canon-v1hp-gsm8k",
      command=p33._gsm8k_command(200),  # pylint: disable=protected-access
      dp_size=16,
      tp_size=4,
      optimizer_resident=True,
      rank_parallel_backward=True,
      fixed_lm_head=True,
      strict_alignment=True,
      v1_hp_full=True,
  )
  gsm_document = p33.render_jobset(
      base, gsm_spec, source_commit, gsm8k_run_id
  )
  gsm_document["metadata"].setdefault("labels", {}).update({
      "canon.zero-tim/performance-profile": "v1-hp",
      "canon.zero-tim/full-recipe": "gsm8k",
  })
  gsm_path = gsm_dir / "jobset-v1-hp-gsm8k-full.yaml"
  _write_yaml(gsm_path, gsm_document)

  p45_outputs = p57.render_all(
      base_path=base_path,
      output_dir=output_dir / "frozenlake-p45",
      source_commit=source_commit,
      run_id=p45_run_id,
      campaign_tag=f"{campaign_root}-p45",
      checkpoint_mode="new",
      expected_updates=300,
      run_kind="train",
      arm="zero",
      high_performance=True,
  )
  m15_outputs = p57.render_all(
      base_path=base_path,
      output_dir=output_dir / "frozenlake-m15",
      source_commit=source_commit,
      run_id=m15_run_id,
      campaign_tag=f"{campaign_root}-m15",
      checkpoint_mode="new",
      expected_updates=300,
      run_kind="train",
      workload_candidate="m15",
      data_split="main",
      arm="zero",
      high_performance=True,
  )
  outputs = (gsm_path, *p45_outputs, *m15_outputs)
  if len(outputs) != 3:
    raise ValueError(f"Phase4 must render exactly three manifests, got {len(outputs)}")
  for path in outputs:
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    _set_env(document, {
        "CANON_P59_CHECKED_VMA": "1",
        "CANON_V1_HP_FIRST_UPDATE_GATE": "1",
    })
    _write_yaml(path, document)

  expected_profiles = {
      "gsm8k": _GSM8K_PROFILE,
      "p45": p57._V1_HP_PROFILE,  # pylint: disable=protected-access
      "m15": p57._V1_HP_PROFILE,  # pylint: disable=protected-access
  }
  receipts = []
  for label, path in zip(("gsm8k", "p45", "m15"), outputs, strict=True):
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    env = _env(document)
    required = {
        "CANON_PROFILE_FILE": expected_profiles[label],
        "CANON_V1_HP_FULL": "1",
        "CANON_P59_RANK_PARALLEL_BACKWARD": "1",
        "CANON_P59_CHECKED_VMA": "1",
        "CANON_V1_HP_FIRST_UPDATE_GATE": "1",
        "CANON_P33_RUN_STAGE": "full",
        "CANON_P33_NO_COMMIT": "0",
        **_JAX_CACHE_ENV,
    }
    if label == "gsm8k":
      required.update({
          "CANON_GSM8K_ALIGNMENT_WARN_ONLY": "0",
          "CANON_P38_FIXED_LM_HEAD": "1",
      })
    else:
      required.update({
          "CANON_FROZENLAKE_ALIGNMENT_WARN_ONLY": "0",
          "CANON_P57_TIM_ARM": "zero",
          "CANON_P57_EXPECTED_UPDATES": "300",
          "CANON_FROZENLAKE_CKPT_MODE": "new",
          "CANON_FROZENLAKE_CKPT_MILESTONE_INTERVAL": "0",
          "CANON_P33_ENABLE_EVAL": "1",
          "CANON_P33_DISABLE_EVAL": "0",
          "CANON_P31_ENABLE_EVAL": "1",
      })
    wrong = {
        name: env.get(name)
        for name, value in required.items()
        if env.get(name) != value
    }
    if wrong:
      raise ValueError(f"{label} rendered V1 contract drifted: {wrong}")
    receipts.append({
        "recipe": label,
        "path": str(path),
        "sha256": _sha256(path),
        "jobset": document["metadata"]["name"],
        "source": source_commit,
    })
    print(
        f"V1_HP_MANIFEST_PASS recipe={label} path={path} "
        f"sha256={receipts[-1]['sha256']}",
        flush=True,
    )
  index = output_dir / "manifest-index.json"
  index.write_text(
      json.dumps({"schema": "v1-hp-three-full-v1", "manifests": receipts}, indent=2)
      + "\n",
      encoding="utf-8",
  )
  print(
      f"V1_HP_THREE_FULL_RENDER_PASS manifests=3 output={output_dir}",
      flush=True,
  )
  return outputs


def main() -> int:
  parser = argparse.ArgumentParser()
  parser.add_argument("--source-commit", required=True)
  parser.add_argument("--output-dir", required=True, type=Path)
  parser.add_argument("--gsm8k-run-id", required=True)
  parser.add_argument("--p45-run-id", required=True)
  parser.add_argument("--m15-run-id", required=True)
  parser.add_argument("--campaign-root", required=True)
  parser.add_argument(
      "--base", type=Path, default=_CLUSTER_DIR / "jobset-64chip.yaml"
  )
  args = parser.parse_args()
  render_three(
      source_commit=args.source_commit,
      output_dir=args.output_dir,
      gsm8k_run_id=args.gsm8k_run_id,
      p45_run_id=args.p45_run_id,
      m15_run_id=args.m15_run_id,
      campaign_root=args.campaign_root,
      base_path=args.base,
  )
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
