#!/usr/bin/env python3
"""Render the two immutable P67 FrozenLake V1 full-training JobSets."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import sys

import yaml


_TASK_DIR = Path(__file__).resolve().parents[1]
_PACKAGE_ROOT = _TASK_DIR.parents[1]
_REPO_ROOT = _PACKAGE_ROOT.parent
_CLUSTER_DIR = _PACKAGE_ROOT / "cluster"
for path in (_REPO_ROOT, _CLUSTER_DIR):
  if str(path) not in sys.path:
    sys.path.insert(0, str(path))

import render_p57_frozenlake_tim as p57


_SHA_RE = re.compile(r"[0-9a-f]{40}")
_PROFILE = p57._V1_HP_PROFILE  # pylint: disable=protected-access
_TOKEN_CONTINUITY_MODES = (
    "legacy",
    "p45-exact",
    "m15-exact",
    "both-exact",
)
_JAX_CACHE_ENV = {
    "JAX_COMPILATION_CACHE_DIR": "/tmp/jax_compilation_cache",
    "JAX_PERSISTENT_CACHE_MIN_COMPILE_TIME_SECS": "0",
    "JAX_PERSISTENT_CACHE_ENABLE_XLA_CACHES": "all",
    "CANON_GCS_CACHE_BUCKET": (
        "gs://yuxzhang-tunix-models/cache/p33_compilation_cache"
    ),
}


def _container(document: dict) -> dict:
  pod = document["spec"]["replicatedJobs"][0]["template"]["spec"][
      "template"
  ]["spec"]
  return next(item for item in pod["containers"] if item["name"] == "jax-tpu")


def _env(document: dict) -> dict[str, str]:
  return {
      item["name"]: item["value"]
      for item in _container(document)["env"]
      if "value" in item
  }


def _set_env(document: dict, values: dict[str, str]) -> None:
  entries = _container(document)["env"]
  existing = {entry["name"] for entry in entries}
  overlap = existing & values.keys()
  if overlap:
    raise ValueError(f"refusing to overwrite rendered env: {sorted(overlap)}")
  entries.extend(
      {"name": name, "value": value} for name, value in values.items()
  )


def _sha256(path: Path) -> str:
  digest = hashlib.sha256()
  with path.open("rb") as source:
    for chunk in iter(lambda: source.read(1024 * 1024), b""):
      digest.update(chunk)
  return digest.hexdigest()


def _write_yaml(path: Path, document: dict) -> None:
  header = (
      "# Generated by v1-phase4 render_p67_frozenlake_two_full_recipes.py.\n"
      "# Do not edit; change the reviewed renderer/profile.\n"
  )
  path.write_text(
      header + yaml.safe_dump(document, sort_keys=False), encoding="utf-8"
  )


def _resolve_token_continuity(
    token_continuity: str | None,
    *,
    m15_tito_exact: bool,
) -> str:
  if token_continuity is not None and m15_tito_exact:
    raise ValueError(
        "--m15-tito-exact cannot be combined with --token-continuity"
    )
  resolved = (
      "m15-exact"
      if m15_tito_exact
      else "legacy"
      if token_continuity is None
      else token_continuity
  )
  if resolved not in _TOKEN_CONTINUITY_MODES:
    raise ValueError(
        "token continuity must be one of "
        f"{_TOKEN_CONTINUITY_MODES}, got {resolved!r}"
    )
  return resolved


def render_two(
    *,
    source_commit: str,
    output_dir: Path,
    p45_run_id: str,
    m15_run_id: str,
    campaign_root: str,
    base_path: Path,
    m15_tito_exact: bool = False,
    token_continuity: str | None = None,
    token_continuity_debug: bool = False,
    token_continuity_debug_mode: str | None = None,
) -> tuple[Path, ...]:
  if not _SHA_RE.fullmatch(source_commit):
    raise ValueError("source commit must be exactly 40 lowercase hex characters")
  if output_dir.exists():
    raise FileExistsError(f"refusing to overwrite output root: {output_dir}")
  if p45_run_id == m15_run_id:
    raise ValueError("P45 and M15 run ids must be distinct")
  token_continuity = _resolve_token_continuity(
      token_continuity, m15_tito_exact=m15_tito_exact
  )
  if token_continuity_debug and token_continuity_debug_mode is not None:
    raise ValueError(
        "--token-continuity-debug and --token-continuity-debug-mode conflict"
    )
  debug_mode = (
      "first-diff" if token_continuity_debug else token_continuity_debug_mode
  )
  if debug_mode not in (None, "first-diff", "record-full"):
    raise ValueError("token-continuity debug mode is not closed")
  if debug_mode is not None and token_continuity == "legacy":
    raise ValueError(
        "token-continuity diagnostics require at least one exact treatment"
    )

  output_dir.mkdir(parents=True)
  p45_outputs = p57.render_all(
      base_path=base_path,
      output_dir=output_dir / "frozenlake-p45",
      source_commit=source_commit,
      run_id=p45_run_id,
      campaign_tag=f"{campaign_root}-p45",
      checkpoint_mode="disabled",
      expected_updates=300,
      run_kind="train",
      arm="zero",
      high_performance=True,
      disable_eval=True,
  )
  m15_outputs = p57.render_all(
      base_path=base_path,
      output_dir=output_dir / "frozenlake-m15",
      source_commit=source_commit,
      run_id=m15_run_id,
      campaign_tag=f"{campaign_root}-m15",
      checkpoint_mode="disabled",
      expected_updates=300,
      run_kind="train",
      workload_candidate="m15",
      data_split="main",
      arm="zero",
      high_performance=True,
      disable_eval=True,
  )
  outputs = (*p45_outputs, *m15_outputs)
  if len(outputs) != 2:
    raise ValueError(f"P67 FrozenLake wave must render two manifests, got {len(outputs)}")

  receipts = []
  for label, path in zip(("p45", "m15"), outputs, strict=True):
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    head = document["spec"]["replicatedJobs"][0]["template"]["spec"][
        "template"
    ]["spec"]
    affinity = head.setdefault("affinity", {})
    pod_anti_affinity = affinity.setdefault("podAntiAffinity", {})
    required_anti_affinity = pod_anti_affinity.setdefault(
        "requiredDuringSchedulingIgnoredDuringExecution", []
    )
    anti_affinity_term = {
        "labelSelector": {
            "matchExpressions": [{
                "key": "jobset.sigs.k8s.io/replicatedjob-name",
                "operator": "In",
                "values": ["pathways-head"],
            }],
        },
        "namespaceSelector": {},
        "topologyKey": "kubernetes.io/hostname",
    }
    if anti_affinity_term not in required_anti_affinity:
      required_anti_affinity.append(anti_affinity_term)
    exact_workloads = {
        "legacy": frozenset(),
        "p45-exact": frozenset({"p45"}),
        "m15-exact": frozenset({"m15"}),
        "both-exact": frozenset({"p45", "m15"}),
    }[token_continuity]
    if label in exact_workloads:
      _set_env(document, {"CANON_P57_TOKEN_CONTINUITY": "exact"})
      if debug_mode is not None:
        _set_env(
            document,
            {"CANON_P57_TOKEN_CONTINUITY_DEBUG": debug_mode},
        )
    _write_yaml(path, document)

    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    env = _env(document)
    required = {
        "CANON_PROFILE_FILE": _PROFILE,
        "CANON_V1_HP_FULL": "1",
        "CANON_P33_SHARED_MESH": "8,8",
        "CANON_P33_RUN_STAGE": "full",
        "CANON_P33_NO_COMMIT": "0",
        "CANON_P57_TIM_ARM": "zero",
        "CANON_P57_EXPECTED_UPDATES": "300",
        "CANON_FROZENLAKE_ALIGNMENT_WARN_ONLY": "1",
        "CANON_P59_RANK_PARALLEL_BACKWARD": "1",
        "CANON_P59_CHECKED_VMA": "1",
        "CANON_P67_P66_VMA_P59_ONLY": "1",
        "CANON_V1_HP_FIRST_UPDATE_GATE": "1",
        "CANON_DP_COMPARE_MODE": "fingerprint-hybrid",
        "CANON_DP_DISTINCT_SCHEDULE": "first-group-warmup",
        "CANON_DP_FINITE_FETCH": "batched-commit",
        "CANON_P71_SCAN": "fwd",
        "CANON_P33_ENABLE_EVAL": "0",
        "CANON_P33_DISABLE_EVAL": "1",
        "CANON_P31_ENABLE_EVAL": "0",
        "CANON_FROZENLAKE_CKPT_MODE": "disabled",
        "CANON_FROZENLAKE_CKPT_ROOT": "",
        "CANON_FROZENLAKE_CKPT_TAG": "",
        "CANON_FROZENLAKE_CKPT_INTERVAL": "",
        "CANON_FROZENLAKE_CKPT_MAX_TO_KEEP": "",
        "CANON_FROZENLAKE_CKPT_MILESTONE_INTERVAL": "",
        **_JAX_CACHE_ENV,
    }
    if label == "p45":
      required.update({
          "CANON_P57_WORKLOAD_CANDIDATE": "",
          "CANON_P57_DATA_SPLIT": "",
      })
    else:
      required.update({
          "CANON_P57_WORKLOAD_CANDIDATE": "m15",
          "CANON_P57_DATA_SPLIT": "main",
      })
    wrong = {
        name: env.get(name)
        for name, value in required.items()
        if env.get(name) != value
    }
    if wrong:
      raise ValueError(f"{label} rendered P67 full contract drifted: {wrong}")
    if "CANON_DP_COLLECTIVE_REDUCE" in env:
      raise ValueError(
          f"{label} rendered an uncertified DP collective reducer"
      )
    if "CANON_M15_TOKEN_CONTINUITY" in env:
      raise ValueError(
          f"{label} must not render the historical M15 TITO selector"
      )
    expected_tito = "exact" if label in exact_workloads else None
    if expected_tito is None and "CANON_P57_TOKEN_CONTINUITY" in env:
      raise ValueError(f"{label} must keep the P57 TITO selector absent")
    if expected_tito is not None and env.get(
        "CANON_P57_TOKEN_CONTINUITY"
    ) != expected_tito:
      raise ValueError(f"{label} exact TITO option was not rendered exactly once")
    expected_debug = (
        debug_mode
        if label in exact_workloads and debug_mode is not None
        else None
    )
    if expected_debug is None and "CANON_P57_TOKEN_CONTINUITY_DEBUG" in env:
      raise ValueError(f"{label} must keep token diagnostics absent")
    if expected_debug is not None and env.get(
        "CANON_P57_TOKEN_CONTINUITY_DEBUG"
    ) != expected_debug:
      raise ValueError(
          f"{label} token diagnostics were not rendered exactly once"
      )
    receipts.append({
        "recipe": label,
        "path": str(path),
        "sha256": _sha256(path),
        "jobset": document["metadata"]["name"],
        "source": source_commit,
    })
    print(
        f"V1_P67_MANIFEST_PASS recipe={label} path={path} "
        f"sha256={receipts[-1]['sha256']}",
        flush=True,
    )

  index = output_dir / "manifest-index.json"
  index.write_text(
      json.dumps({
          "schema": "v1-p67-frozenlake-two-full-v2",
          "token_continuity": token_continuity,
          "token_continuity_debug": debug_mode,
          "manifests": receipts,
      }, indent=2) + "\n",
      encoding="utf-8",
  )
  print(
      f"V1_P67_FROZENLAKE_TWO_FULL_RENDER_PASS manifests=2 output={output_dir}",
      flush=True,
  )
  return outputs


def main() -> int:
  parser = argparse.ArgumentParser()
  parser.add_argument("--source-commit", required=True)
  parser.add_argument("--output-dir", required=True, type=Path)
  parser.add_argument("--p45-run-id", required=True)
  parser.add_argument("--m15-run-id", required=True)
  parser.add_argument("--campaign-root", required=True)
  parser.add_argument(
      "--m15-tito-exact",
      action="store_true",
      help="deprecated alias for --token-continuity=m15-exact",
  )
  parser.add_argument(
      "--token-continuity",
      choices=_TOKEN_CONTINUITY_MODES,
      help="select exact token transport per workload; default is legacy",
  )
  parser.add_argument(
      "--token-continuity-debug",
      action="store_true",
      help="persist and log the first exact token mismatch; default is off",
  )
  parser.add_argument(
      "--token-continuity-debug-mode",
      choices=("first-diff", "record-full"),
      help="select the closed diagnostic policy; default is absent",
  )
  parser.add_argument(
      "--base", type=Path, default=_CLUSTER_DIR / "jobset-64chip.yaml"
  )
  args = parser.parse_args()
  render_two(
      source_commit=args.source_commit,
      output_dir=args.output_dir,
      p45_run_id=args.p45_run_id,
      m15_run_id=args.m15_run_id,
      campaign_root=args.campaign_root,
      base_path=args.base,
      m15_tito_exact=args.m15_tito_exact,
      token_continuity=args.token_continuity,
      token_continuity_debug=args.token_continuity_debug,
      token_continuity_debug_mode=args.token_continuity_debug_mode,
  )
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
