#!/usr/bin/env python3
"""Render one immutable P62 GSM8K backward-no-commit diagnostic JobSet."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import sys

import yaml


_TASK_DIR = Path(__file__).resolve().parents[1]
_PACKAGE_ROOT = _TASK_DIR.parents[1]
_REPO_ROOT = _PACKAGE_ROOT.parent
_CLUSTER_DIR = _PACKAGE_ROOT / "cluster"
for path in (_REPO_ROOT, _CLUSTER_DIR):
  if str(path) not in sys.path:
    sys.path.insert(0, str(path))

import render_p33_jobsets as p33


_SHA_RE = re.compile(r"[0-9a-f]{40}")
_PROFILE = "cluster/profiles/qwen3-1p7b-dp16-tp4-gsm8k-p62-debug.env"


def _sha256(path: Path) -> str:
  digest = hashlib.sha256()
  with path.open("rb") as source:
    for chunk in iter(lambda: source.read(1024 * 1024), b""):
      digest.update(chunk)
  return digest.hexdigest()


def _env(document: dict) -> dict[str, str]:
  pod = document["spec"]["replicatedJobs"][0]["template"]["spec"][
      "template"
  ]["spec"]
  main = next(
      item for item in pod["containers"] if item["name"] == "jax-tpu"
  )
  return {
      item["name"]: item["value"]
      for item in main["env"]
      if "value" in item
  }


def render(
    *, source_commit: str, run_id: str, output_dir: Path, base_path: Path
) -> Path:
  if not _SHA_RE.fullmatch(source_commit):
    raise ValueError("source commit must be exactly 40 lowercase hex")
  if output_dir.exists():
    raise FileExistsError(f"refusing to overwrite output root: {output_dir}")
  output_dir.mkdir(parents=True)
  spec = p33.JobSpec(
      key="gsm8k-p62-numeric-debug",
      workload="gsm8k",
      stage="backward-no-commit",
      profile=_PROFILE,
      no_commit=True,
      job_prefix="canon-p62-gsm8k-num",
      command=p33._gsm8k_command(1),  # pylint: disable=protected-access
      dp_size=16,
      tp_size=4,
      optimizer_resident=True,
      rank_parallel_backward=True,
      fixed_lm_head=True,
      strict_alignment=True,
      v1_hp_full=False,
      backward_numeric_debug=True,
  )
  document = p33.render_jobset(
      p33.load_base(base_path), spec, source_commit, run_id
  )
  document["metadata"].setdefault("labels", {}).update({
      "canon.zero-tim/diagnostic": "p62-backward-numeric",
      "canon.zero-tim/optimizer-commits": "0",
  })
  values = _env(document)
  required = {
      "CANON_PROFILE_FILE": _PROFILE,
      "CANON_P33_RUN_STAGE": "backward-no-commit",
      "CANON_P33_NO_COMMIT": "1",
      "CANON_P59_RANK_PARALLEL_BACKWARD": "1",
      "CANON_P38_FIXED_LM_HEAD": "1",
      "CANON_P62_BACKWARD_NUMERIC_DEBUG": "1",
      "CANON_V1_HP_FULL": "0",
      "CANON_GSM8K_ALIGNMENT_WARN_ONLY": "0",
  }
  wrong = {
      name: values.get(name)
      for name, expected in required.items()
      if values.get(name) != expected
  }
  if wrong:
    raise ValueError(f"rendered P62 contract drifted: {wrong}")
  output = output_dir / "jobset-p62-gsm8k-numeric-debug.yaml"
  output.write_text(
      "# Generated by render_attempt7_numeric_debug.py. Do not edit.\n"
      + yaml.safe_dump(document, sort_keys=False),
      encoding="utf-8",
  )
  receipt = {
      "schema": "canon-p62-render-v1",
      "source_commit": source_commit,
      "run_id": run_id,
      "jobset": document["metadata"]["name"],
      "path": str(output),
      "sha256": _sha256(output),
      "optimizer_commits": 0,
  }
  (output_dir / "render-receipt.json").write_text(
      json.dumps(receipt, indent=2, sort_keys=True) + "\n",
      encoding="utf-8",
  )
  print(
      "P62_NUMERIC_RENDER_PASS "
      f"jobset={receipt['jobset']} sha256={receipt['sha256']} "
      "optimizer_commits=0",
      flush=True,
  )
  return output


def main() -> int:
  parser = argparse.ArgumentParser()
  parser.add_argument("--source-commit", required=True)
  parser.add_argument("--run-id", required=True)
  parser.add_argument("--output-dir", required=True, type=Path)
  parser.add_argument(
      "--base",
      type=Path,
      default=_CLUSTER_DIR / "jobset-64chip.yaml",
  )
  args = parser.parse_args()
  render(
      source_commit=args.source_commit,
      run_id=args.run_id,
      output_dir=args.output_dir,
      base_path=args.base,
  )
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
