repos:
  - repo: https://github.com/google/pyink
    rev: '24.10.1'
    hooks:
      - id: pyink
        types_or: [python, jupyter]
        files: '\.(py|ipynb)$'
        additional_dependencies:
          - "pyink[jupyter]"

  - repo: https://github.com/pylint-dev/pylint
    rev: v3.3.8
    hooks:
      - id: pylint
        name: pylint
        types: [python]
        verbose: true
        args:
          - --rcfile=.pylintrc
          # Prevents pylint from failing the pre-commit hook. This is necessary
          # because pylint is very strict.
          - --exit-zero
        exclude: ^tests/

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-pylint
        stages: [manual]
        additional_dependencies: [pylint==3.3.8]
        args: [--rcfile=.pylintrc-notebooks, --fail-under=10.0]
        files: '\.ipynb$'

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        args: ["--wrap", "80"]
        additional_dependencies:
          - mdformat-gfm==0.3.5
          - "markdown-it-py[linkify]"
          # (optional) other plugins:
          # - mdformat-frontmatter
          # - mdformat-tables
        files: '\.md$'

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
    - id: isort
      name: isort
      types: [python]
      exclude: ^tests/
