apiVersion: v1
kind: Pod
metadata:
  name: cache-downloader
spec:
  containers:
  - name: downloader
    image: python:3.12-slim
    command: ["sleep", "86400"]
    volumeMounts:
    - mountPath: /mnt/disks/linchai_data
      name: linchai-gke-disk-2
  volumes:
  - name: linchai-gke-disk-2
    persistentVolumeClaim:
      claimName: linchai-cpu-np-pvc-2
