FROM gcr.io/cloud-tpu-multipod-dev/anisha-tmvp/anisha-0825:igorts-chunk4-v2

ENV PATH="/opt/venv/bin:$PATH"

# Reinstall the Raiden wheel with FFI support
COPY .docker/tpu_sync/*.whl /tmp/tpu_sync/
RUN pip install --force-reinstall --no-deps /tmp/tpu_sync/*.whl && rm -rf /tmp/tpu_sync

# Install local MaxText
COPY .docker/maxtext /maxtext
RUN pip install --no-deps -e /maxtext

# Install local Tunix
WORKDIR /app
COPY . /app
RUN pip install --no-deps -e /app

CMD ["bash"]
