#!/usr/bin/env python3
"""Build figure4.xlsx: the Figure 4 curves, recipe and provenance in one workbook.

Every value comes from data/manifest.json and data/*.csv; nothing is typed by
hand. The raw curve columns hold the CSV's original number strings, so a reader
sees exactly the digits that were plotted. The ten-step trailing average reuses
moving_average() from the figure builder, so solve_trail10 at display step 200
is the endpoint label the figure prints.

Run from this directory (needs openpyxl and PyYAML):
    python make_spreadsheet.py            # writes ./figure4.xlsx
    python make_spreadsheet.py --output /tmp/other.xlsx
"""

from __future__ import annotations

import argparse
from pathlib import Path

from openpyxl import Workbook

import build_end_to_end_results_measured as figure
# Same trailing-mean function the figure's foreground curve and endpoint labels
# use (build_end_to_end_results_measured re-exports it from this module).
from build_end_to_end_results_provisional import moving_average

ROOT = Path(__file__).resolve().parent
DATA = ROOT / "data"
WANDB_PROJECT = "zero-tim-p57-frozenlake-tim"
ARMS = (("standard", "Standard"),
        ("importance_sampling", "Token-level TIS"),
        ("zero_tim", "Zero-TIM"))
METRICS = (("solve_ratio", figure.REWARD),
           ("solve_trail10", None),
           ("logp_diff_mean", figure.MEAN))
SHEETS = ("README", "curves_wide", "curves_long", "recipe", "provenance", "endpoints")
EVIDENCE = "analysis-grade telemetry, not signed full-run certification"
BRANCH_TIP = "see README.md"


def cell(value):
    """Render a manifest scalar for a spreadsheet cell without inventing values."""
    return "null" if value is None else value


def build(output: Path) -> Path:
    selected, manifest = figure.load_exported_data(DATA)
    run = figure.make_workload(selected)
    trail = {arm: moving_average(run.solve_rate[figure.DRAWING_KEYS[arm]])
             for arm, _ in ARMS}

    book = Workbook()
    readme = book.active
    readme.title = "README"
    readme.append(["sheet", "contents"])
    for name, description in (
        ("README", "This sheet: what each tab holds, where the numbers come from."),
        ("curves_wide", "Display step 1-200, then per arm: solve_ratio, solve_trail10, "
                        "logp_diff_mean. One row per training observation."),
        ("curves_long", "The same numbers tidy: arm, step, metric, value."),
        ("recipe", "One row per run-config key, one column per arm, plus differs=TRUE "
                   "where the three arms disagree."),
        ("provenance", "Run ids, W&B project, executed source SHA, and the sha256 of "
                       "every source file behind the curves."),
        ("endpoints", "Per arm and metric: last_ten_mean, minimum, maximum, exactly as "
                      "recorded in data/manifest.json."),
    ):
        readme.append([name, description])
    readme.append([])
    for key, value in (
        ("evidence grade", EVIDENCE),
        ("manifest evidence_grade", manifest["evidence_grade"]),
        ("signed_full_run_certification", manifest["signed_full_run_certification"]),
        ("archive commit", manifest["source_commit"]),
        ("branch tip", BRANCH_TIP),
        ("W&B project", WANDB_PROJECT),
        ("plotted window", f"source steps {manifest['window']['source_step_first']}-"
                           f"{manifest['window']['source_step_last']} shown as display steps "
                           f"{manifest['window']['display_step_first']}-"
                           f"{manifest['window']['display_step_last']}, "
                           f"{manifest['window']['count_per_arm']} per arm"),
        ("trailing window", manifest["transformations"]["trailing_window"]),
        ("generated by", "make_spreadsheet.py from data/manifest.json and data/*.csv"),
        ("raw columns", "solve_ratio and logp_diff_mean are stored as text: they are the "
                        "CSV's own digits, not re-formatted numbers. solve_trail10 is numeric."),
        ("numeric precision", "Numeric cells (solve_trail10, endpoints) are written at the "
                              "spreadsheet's float precision, which can drop the last digit or "
                              "two; data/manifest.json holds the full value."),
    ):
        readme.append([key, value])

    wide = book.create_sheet("curves_wide")
    wide.append(["display_step"] + [f"{label} {metric}" for _, label in ARMS
                                    for metric, _ in METRICS])
    long = book.create_sheet("curves_long")
    long.append(["arm", "step", "metric", "value"])
    for index in range(figure.STEPS):
        step = trail[ARMS[0][0]][index].update
        row = [step]
        for arm, label in ARMS:
            source = selected[arm][index]
            assert int(float(source["_step"])) + 1 == step, "arm steps out of step"
            row += [source[figure.REWARD], trail[arm][index].value, source[figure.MEAN]]
            for metric, key in METRICS:
                value = trail[arm][index].value if key is None else source[key]
                long.append([label, step, metric, value])
        wide.append(row)

    recipe = book.create_sheet("recipe")
    recipe.append(["config_key"] + [label for _, label in ARMS] + ["differs"])
    configs = [manifest["runs"][arm]["config"] for arm, _ in ARMS]
    for other in configs[1:]:
        assert set(other) == set(configs[0]), "arms disagree on config keys"
    for key in configs[0]:
        values = [config[key] for config in configs]
        recipe.append([key] + [cell(value) for value in values]
                      + [not all(value == values[0] for value in values)])

    provenance = book.create_sheet("provenance")
    provenance.append(["arm", "run_id", "wandb_project", "executed_source_sha",
                       "source_history", "source_history_sha256",
                       "source_config", "source_config_sha256",
                       "plotted_csv", "plotted_csv_sha256",
                       "source_csv_line_first", "source_csv_line_last"])
    for arm, label in ARMS:
        entry = manifest["runs"][arm]
        lines = entry["source_csv_lines"]
        provenance.append([label, entry["run_id"], WANDB_PROJECT,
                           entry["run_id"].rsplit("-", 1)[-1],
                           entry["source_history"], entry["source_history_sha256"],
                           entry["source_config"], entry["source_config_sha256"],
                           entry["plotted_csv"], entry["plotted_csv_sha256"],
                           lines[0], lines[-1]])

    endpoints = book.create_sheet("endpoints")
    endpoints.append(["arm", "metric", "last_ten_mean", "minimum", "maximum"])
    for arm, label in ARMS:
        for metric, stats in manifest["runs"][arm]["metrics"].items():
            endpoints.append([label, metric, stats["last_ten_mean"],
                              stats["minimum"], stats["maximum"]])

    assert book.sheetnames == list(SHEETS), book.sheetnames
    for sheet in book:
        sheet.column_dimensions["A"].width = 34
        sheet.column_dimensions["B"].width = 34
    book.save(output)
    return output


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "figure4.xlsx")
    args = parser.parse_args()
    path = build(args.output)
    print(f"PASS: wrote {path} ({path.stat().st_size} bytes) from {DATA}")


if __name__ == "__main__":
    main()
