# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Sampler abstractions for Distributed-RL."""

import dataclasses
from typing import Any, Protocol, Sequence, runtime_checkable

from jax import typing
import numpy as np
from tunix.experimental.common import datatypes
# The transport-neutral contracts module: `WorkUnitMetadata` is the shape the
# coordinator registers with whatever transport handler is installed. It
# carries no Raiden types, so depending on it does not couple the rollout
# layer to a transport.
from tunix.experimental.orchestrator import weight_sync as weight_sync_lib

ArrayLike = typing.ArrayLike


@dataclasses.dataclass(kw_only=True)
class SamplingParams:
  """Engine-neutral sampling configuration for a generation request.

  Attributes:
    max_tokens: Maximum number of tokens to generate.
    temperature: Softmax temperature applied while sampling. Kept explicit so it
      can be carried through to any later log-probability scoring, ensuring the
      sampling distribution and the scoring distribution match.
    top_p: Nucleus sampling probability threshold.
    top_k: Top-k sampling candidate count threshold.
    seed: Random seed for reproducible generation.
    return_logprobs: Whether to record per-token log probabilities.
    return_logits: Whether to record per-token output logits.
    beam_size: Beam width for beam search decoding.
  """

  max_tokens: int = 64
  temperature: float = 1.0
  top_p: float | None = None
  top_k: int | None = None
  seed: int | None = None
  return_logprobs: bool = False
  return_logits: bool = False
  beam_size: int | None = None


@dataclasses.dataclass(kw_only=True)
class SamplingRequest(datatypes.Request):
  """Request to generate completions for a single prompt from a Sampler.

  Attributes:
    prompt: The source prompt to sample from (formatted string, token array, or
      chat dictionary).
    sampling_params: Optional per-request sampling configuration.
  """

  prompt: Any
  sampling_params: SamplingParams | None = None


@dataclasses.dataclass(kw_only=True)
class SamplingResponse(datatypes.Response):
  """Serializable result of a single sampling/completion request from a Sampler.

  Attributes:
    text: Detokenized completion text string generated by the model.
    prompt_token_ids: Array of prompt token IDs as tokenized by the sampler
      backend, with backend padding removed.
    token_ids: Array of generated token IDs (unpadded).
    logprobs: Array of per-token log-probabilities under the sampling policy
      (required for RL), or None if not requested.
    finish_reason: Reason generation terminated (e.g., "stop", "length",
      "cancelled", "error").
    error: Structured failure details when sampling failed for this prompt, else
      None (inherited from datatypes.Response).
    routed_experts: Array of routed expert IDs of shape [Batch, Layers, Length,
      Top K], or None if not requested.
  """

  text: str = ""
  prompt_token_ids: np.ndarray = dataclasses.field(
      default_factory=lambda: np.zeros(0, dtype=np.int32)
  )
  token_ids: np.ndarray = dataclasses.field(
      default_factory=lambda: np.zeros(0, dtype=np.int32)
  )
  logprobs: np.ndarray | None = None
  finish_reason: str = "stop"
  routed_experts: ArrayLike | None = None

  def __post_init__(self):
    if (
        self.logprobs is not None
        and self.logprobs.shape != self.token_ids.shape
    ):
      raise ValueError(
          f"logprobs shape {self.logprobs.shape} != token_ids shape"
          f" {self.token_ids.shape}"
      )


# One canonical request type crosses trainer, coordinator, and rollout-worker
# process boundaries.  Keep this alias for callers that historically imported
# it from sampler.py, but do not define a second dataclass here: CL4 constructs
# `datatypes.WeightSyncRequest`, and two merely duck-compatible classes make
# type checking and cloudpickle compatibility depend on which import a caller
# happened to use.
WeightSyncRequest = datatypes.WeightSyncRequest


@dataclasses.dataclass(kw_only=True)
class LoadInfo(datatypes.Response):
  """Load information for a Sampler."""
  num_requests_waiting: int = 0
  num_requests_running: int = 0
  kv_cache_usage_perc: float = 0.0


@runtime_checkable
class Sampler(Protocol):
  """Protocol defining standard lifecycle, sampling, and weight-sync interface for worker slices."""

  # --- Lifecycle & Topology ---
  def initialize(self) -> None:
    """Initializes backend resources before serving requests."""
    ...

  async def start(self, **kwargs) -> str | None | Any:
    """Starts the sampling server engine or local loop."""
    ...

  async def stop(self, **kwargs) -> str | None | Any:
    """Terminates sampler execution and closes local connections."""
    ...

  async def pause(self, **kwargs) -> str | None | Any:
    """Pauses inference processing on this worker slice."""
    ...

  async def resume(self, **kwargs) -> str | None | Any:
    """Resumes inference processing on this worker slice."""
    ...

  async def get_mesh(self, **kwargs) -> Any:
    """Returns the underlying device mesh topology."""
    ...

  # --- Inference ---
  async def sample(
      self,
      sampling_requests: (
          SamplingRequest
          | Sequence[SamplingRequest]
          | Any
          | Sequence[Any]
      ),
      **kwargs,
  ) -> list[SamplingResponse] | Any:
    """Generates completions for a batch of prompt conversations concurrently."""
    ...

  # --- Weight Synchronization ---
  async def get_weight_sync_metadata(
      self, **kwargs
  ) -> Sequence[weight_sync_lib.WorkUnitMetadata]:
    """Returns the registration metadata for this sampler's policy weights.

    One entry per physical host. Variable names inside the manifest are the
    names the transfer pairs BY EXACT STRING against the source side; a
    mismatch is silently skipped by the planner, so they must come from the
    shared model mapping, never be hand-written.
    """
    ...

  async def pre_weight_sync(
      self, sync_request: datatypes.WeightSyncRequest | None = None, **kwargs
  ) -> str | None | Any:
    """Quiesces inference and prepares staging for a policy update."""
    ...

  async def weight_sync(
      self, sync_request: datatypes.WeightSyncRequest | None = None, **kwargs
  ) -> str | None | Any:
    """Materializes the requested policy weights into inactive staging."""
    ...

  async def post_weight_sync(
      self, sync_request: datatypes.WeightSyncRequest | None = None, **kwargs
  ) -> str | None | Any:
    """Finalizes and switches active policy weights after transfer completion."""
    ...

  async def get_transfer_status(
      self, req_id: str | Any, **kwargs
  ) -> str | Any:
    """Queries the status of an ongoing weight transfer or KV-cache migration request."""
    ...

  async def migrate_kv_cache(
      self,
      source_server_id: str,
      target_server_id: str,
      token_ids: list[int],
      **kwargs,
  ) -> bool:
    """Triggers KV-cache migration from source to target slice."""
    ...

  async def get_load_info(self, **kwargs) -> LoadInfo | Any:
    """Returns the current load information for this sampler."""
    ...


# TODO: Converge this capability protocol onto the shared
# WeightSyncDestination contract in orchestrator/weight_sync.py so the weight
# sync protocol has one source of truth.
@runtime_checkable
class WeightSyncCapableSampler(Protocol):
  """Optional coordinated-weight-sync capability layered on `Sampler`.

  Kept out of `Sampler` deliberately: a `runtime_checkable` isinstance check
  tests member PRESENCE only, so folding these three in would make every
  sampler that predates coordinated weight sync fail the `Sampler` check and
  stop constructing. A sampler that drives rounds satisfies both protocols;
  this one is checked only when a round actually needs the capability, never
  on the sampling path.
  """

  async def bind_weight_sync(self, **kwargs) -> Any:
    """Initializes destination-side weight-sync resources if absent.

    This sampler-level method is a facade: any resource that must live beside
    device arrays is constructed by delegating to the TPU worker/process that
    owns those arrays.  It is idempotent and called every round. Existing
    externally advertised endpoints remain stable; rebinding an inactive
    staging set is allowed.
    """
    raise NotImplementedError(
        "this sampler does not implement coordinated weight sync"
    )

  async def abort_weight_sync(
      self, sync_request: datatypes.WeightSyncRequest | None = None, **kwargs
  ) -> Any:
    """Rolls back to serving the previous weights. Safe at any phase."""
    raise NotImplementedError(
        "this sampler does not implement coordinated weight sync"
    )

  async def get_weight_sync_status(self, **kwargs) -> Any:
    """The round report the coordinator reconciles failed RPCs against."""
    raise NotImplementedError(
        "this sampler does not implement coordinated weight sync"
    )
