FROM us-central1-docker.pkg.dev/cloud-tpu-multipod-dev/yangmu/tunix/tunix_base_image:trellis-demo-0813

ENV PATH="/opt/venv/bin:$PATH"

RUN pip install --no-cache-dir -U "jax[tpu]==0.11.0" "jaxlib==0.11.0" "libtpu==0.0.44" \
    -f https://storage.googleapis.com/jax-releases/libtpu_releases.html

WORKDIR /app
COPY . /app

RUN bash scripts/install_tunix_vllm_requirement.sh

RUN pip install --no-deps -e /app

CMD ["bash"]
