#!/usr/bin/env python3
"""Render isolated DP8xTP8 resident FrozenLake full/eval JobSets."""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys

import yaml

_CLUSTER_DIR = Path(__file__).resolve().parent
if str(_CLUSTER_DIR) not in sys.path:
  sys.path.insert(0, str(_CLUSTER_DIR))

from render_p33_jobsets import JobSpec
from render_p33_jobsets import _frozenlake_command
from render_p33_jobsets import load_base
from render_p33_jobsets import render_jobset


_PROFILE = "cluster/profiles/qwen3-8b-dp8-tp8-frozenlake-resident.env"
_CHECKPOINT_ROOT = (
    "gs://yuxzhang-tunix-models/canon-zero-tim/checkpoints/frozenlake"
)
_CHECKPOINT_TAG_RE = re.compile(
    r"[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?"
)
_BASE_JAX_MEMORY_LIMIT = "200G"
_P45_JAX_MEMORY_LIMIT = "350G"
_SPECS = (
    JobSpec(
        key="frozenlake-full-dp8-tp8-resident",
        workload="frozenlake",
        stage="full",
        profile=_PROFILE,
        no_commit=False,
        job_prefix="canon-p45-fl-res",
        command=_frozenlake_command(450, dp_size=8, tp_size=8),
        dp_size=8,
        tp_size=8,
        optimizer_resident=True,
    ),
    JobSpec(
        key="frozenlake-full-dp8-tp8-resident-eval",
        workload="frozenlake",
        stage="full",
        profile=_PROFILE,
        no_commit=False,
        job_prefix="canon-p45-fl-eval",
        command=_frozenlake_command(
            450, enable_evaluation=True, dp_size=8, tp_size=8
        ),
        enable_evaluation=True,
        dp_size=8,
        tp_size=8,
        optimizer_resident=True,
    ),
)


def render_all(
    *,
    base_path: Path,
    output_dir: Path,
    source_commit: str,
    run_id: str,
    checkpoint_tag: str,
    checkpoint_mode: str,
) -> tuple[Path, ...]:
  """Renders the two P45 variants without modifying the P33 queue."""
  if checkpoint_mode not in ("new", "resume"):
    raise ValueError("P45 checkpoint mode must be new or resume")
  if not _CHECKPOINT_TAG_RE.fullmatch(checkpoint_tag):
    raise ValueError(
        "P45 checkpoint tag must be lowercase, Kubernetes-safe, and at most "
        "63 characters"
    )
  base = load_base(base_path)
  output_dir.mkdir(parents=True, exist_ok=True)
  outputs = tuple(
      output_dir / f"jobset-p45-{spec.key}.yaml" for spec in _SPECS
  )
  existing = [path for path in outputs if path.exists()]
  if existing:
    raise FileExistsError(
        "refusing to overwrite rendered P45 JobSets: "
        + ", ".join(str(path) for path in existing)
    )
  for spec, path in zip(_SPECS, outputs, strict=True):
    document = render_jobset(base, spec, source_commit, run_id)
    head_pod = document["spec"]["replicatedJobs"][0]["template"]["spec"][
        "template"
    ]["spec"]
    main = next(
        item for item in head_pod["containers"] if item["name"] == "jax-tpu"
    )
    resources = main.get("resources", {})
    limits = resources.get("limits", {})
    if limits.get("memory") != _BASE_JAX_MEMORY_LIMIT:
      raise ValueError(
          "P45 base jax-tpu memory limit drifted: "
          f"{limits.get('memory')!r} vs {_BASE_JAX_MEMORY_LIMIT!r}"
      )
    limits["memory"] = _P45_JAX_MEMORY_LIMIT
    checkpoint_values = {
        "CANON_FROZENLAKE_CKPT_MODE": checkpoint_mode,
        "CANON_FROZENLAKE_CKPT_ROOT": _CHECKPOINT_ROOT,
        "CANON_FROZENLAKE_CKPT_TAG": checkpoint_tag,
        "CANON_FROZENLAKE_CKPT_INTERVAL": "10",
        "CANON_FROZENLAKE_CKPT_MAX_TO_KEEP": "1",
    }
    env_by_name = {entry["name"]: entry for entry in main["env"]}
    for name, value in checkpoint_values.items():
      if name in env_by_name:
        raise ValueError(f"base P45 manifest already defines {name}")
      main["env"].append({"name": name, "value": value})
    resolved = {
        entry["name"]: entry.get("value")
        for entry in main["env"]
        if "value" in entry
    }
    wrong = {
        name: resolved.get(name)
        for name, expected in checkpoint_values.items()
        if resolved.get(name) != expected
    }
    if wrong:
      raise ValueError(f"P45 checkpoint render contract drifted: {wrong}")
    if resolved.get("ENABLE_PATHWAYS_PERSISTENCE", "1") != "1":
      raise ValueError("P45 checkpoint render requires Pathways persistence")
    if main["resources"]["limits"].get("memory") != _P45_JAX_MEMORY_LIMIT:
      raise ValueError("P45 jax-tpu memory limit override was not retained")
    header = (
        "# Generated by canon-zero-tim/cluster/render_p45_frozenlake.py.\n"
        "# Do not edit this output; change the reviewed base or renderer.\n"
    )
    path.write_text(
        header + yaml.safe_dump(document, sort_keys=False), encoding="utf-8"
    )
    print(f"[P45.JOBSET] RENDERED key={spec.key} path={path}")
  return outputs


def main() -> int:
  parser = argparse.ArgumentParser()
  parser.add_argument("--source-commit", required=True)
  parser.add_argument("--run-id", required=True)
  parser.add_argument("--output-dir", required=True, type=Path)
  parser.add_argument("--checkpoint-tag", required=True)
  parser.add_argument(
      "--checkpoint-mode", choices=("new", "resume"), default="new"
  )
  parser.add_argument(
      "--base",
      type=Path,
      default=Path(__file__).with_name("jobset-64chip.yaml"),
  )
  args = parser.parse_args()
  outputs = render_all(
      base_path=args.base,
      output_dir=args.output_dir,
      source_commit=args.source_commit,
      run_id=args.run_id,
      checkpoint_tag=args.checkpoint_tag,
      checkpoint_mode=args.checkpoint_mode,
  )
  print(
      "[P45.JOBSET] VERDICT PASS "
      f"count={len(outputs)} source={args.source_commit} run_id={args.run_id} "
      f"checkpoint_tag={args.checkpoint_tag} "
      f"checkpoint_mode={args.checkpoint_mode}"
  )
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
