#!/usr/bin/env python3
"""Render the one strict P35 GSM8K envelope-short JobSet."""

from __future__ import annotations

import argparse
import importlib.util
from pathlib import Path
import shlex
import sys
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[2]
P33_RENDERER = Path(__file__).with_name("render_p33_jobsets.py")
MODULE_SPEC = importlib.util.spec_from_file_location(
    "p35_p33_renderer", P33_RENDERER
)
if MODULE_SPEC is None or MODULE_SPEC.loader is None:
  raise RuntimeError("cannot import the P33 JobSet renderer")
p33 = importlib.util.module_from_spec(MODULE_SPEC)
sys.modules[MODULE_SPEC.name] = p33
MODULE_SPEC.loader.exec_module(p33)


def _command() -> tuple[str, ...]:
  return (
      "python3",
      "-u",
      "examples/math_gsm8k/qwen3_grpo_demo.py",
      *p33._common_args(max_steps=1, prompt=1024, response=64),
      "--train_micro_batch_size=32",
      "--compute_logps_micro_batch_size=32",
      "--rollout_vllm_hbm_utilization=0.20",
      "--rollout_vllm_max_num_seqs=16",
      "--rollout_vllm_max_num_batched_tokens=256",
      "--wandb_project=zero-tim-gsm8k-dp16-tp4",
  )


SPEC = p33.JobSpec(
    key="gsm8k-envelope-short",
    workload="gsm8k",
    stage="envelope-short",
    profile="cluster/profiles/qwen3-1p7b-dp16-tp4-gsm8k.env",
    no_commit=True,
    job_prefix="canon-p35-gsm8k-env",
    command=_command(),
)


def _main_env(document: dict[str, Any]) -> list[dict[str, Any]]:
  head = p33._head_pod(document)
  return p33._container(head["containers"], "jax-tpu")["env"]


def render(
    *, base_path: Path, source_commit: str, run_id: str
) -> dict[str, Any]:
  """Returns one source-pinned P35 JobSet with isolated evidence paths."""
  document = p33.render_jobset(
      p33.load_base(base_path), SPEC, source_commit, run_id
  )
  env_values = p33._env_values(document)
  state = env_values["CANON_STATE"]
  p33._set_named_env(
      _main_env(document),
      {
          "CANON_P35_ENVELOPE": "1",
          "CANON_P35_ENVELOPE_REPORT": f"{state}/p35_envelope.json",
          "CANON_P35_METADATA_DIR": f"{state}/p35_metadata",
          "CANON_P35_CLASSIFICATION": f"{state}/p35_envelope.classification.json",
      },
      remove=(),
  )
  validate(document, source_commit=source_commit, run_id=run_id)
  return document


def validate(document: dict[str, Any], *, source_commit: str, run_id: str) -> None:
  """Rejects a P35 manifest that could train or overwrite evidence."""
  p33.validate_jobset(document, SPEC, source_commit, run_id)
  env = p33._env_values(document)
  state = env["CANON_STATE"]
  expected = {
      "CANON_P35_ENVELOPE": "1",
      "CANON_P35_ENVELOPE_REPORT": f"{state}/p35_envelope.json",
      "CANON_P35_METADATA_DIR": f"{state}/p35_metadata",
      "CANON_P35_CLASSIFICATION": f"{state}/p35_envelope.classification.json",
      "CANON_P33_RUN_STAGE": "envelope-short",
      "CANON_P33_NO_COMMIT": "1",
      "CANON_PRE_ALIGN_GATE": "1",
      "CANON_RUN_CMD": shlex.join(_command()),
  }
  wrong = {key: env.get(key) for key, value in expected.items() if env.get(key) != value}
  if wrong:
    raise ValueError(f"generated P35 environment drifted: {wrong}")
  command = env["CANON_RUN_CMD"]
  if "--max_response_length=64" not in command or "--max_steps=1" not in command:
    raise ValueError("P35 command lost its response or step bound")


def main() -> int:
  parser = argparse.ArgumentParser()
  parser.add_argument("--source-commit", required=True)
  parser.add_argument("--run-id", required=True)
  parser.add_argument("--output", required=True, type=Path)
  parser.add_argument(
      "--base",
      type=Path,
      default=Path(__file__).with_name("jobset-64chip.yaml"),
  )
  args = parser.parse_args()
  if args.output.exists():
    raise FileExistsError(f"refusing to overwrite {args.output}")
  document = render(
      base_path=args.base,
      source_commit=args.source_commit,
      run_id=args.run_id,
  )
  args.output.parent.mkdir(parents=True, exist_ok=True)
  args.output.write_text(
      "# Generated by canon-zero-tim/cluster/render_p35_jobset.py.\n"
      + yaml.safe_dump(document, sort_keys=False),
      encoding="utf-8",
  )
  print(f"[P35.JOBSET] RENDERED path={args.output}")
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
