#!/usr/bin/env python3
"""Render bounded FrozenLake serving-capture and KV-unified JobSets."""

from __future__ import annotations

import argparse
import importlib.util
from pathlib import Path
import sys
from typing import Any, Mapping

import yaml


_P33_PATH = Path(__file__).with_name("render_p33_jobsets.py")
_P33_SPEC = importlib.util.spec_from_file_location("render_p33_jobsets", _P33_PATH)
assert _P33_SPEC and _P33_SPEC.loader
p33 = importlib.util.module_from_spec(_P33_SPEC)
sys.modules[_P33_SPEC.name] = p33
_P33_SPEC.loader.exec_module(p33)

_CAPTURE_PREFIX_BOUNDS = (1536, 1792, 2048, 2304, 2560)
_CAPTURE_RECORDS = len(_CAPTURE_PREFIX_BOUNDS) - 1


def _spec(*, unified: bool) -> Any:
  suffix = "unified" if unified else "stock"
  return p33.JobSpec(
      key=f"p38-serving-{suffix}",
      workload="frozenlake",
      stage="backward-no-commit",
      profile="cluster/profiles/qwen3-8b-dp16-tp4-frozenlake.env",
      no_commit=True,
      job_prefix=f"canon-p38-fl-{suffix}",
      command=p33._frozenlake_command(1),
  )


_SPECS = ((_spec(unified=False), False), (_spec(unified=True), True))


def _main_container(document: Mapping[str, Any]) -> dict[str, Any]:
  return p33._container(p33._head_pod(document)["containers"], "jax-tpu")


def _capture_values(document: Mapping[str, Any], *, unified: bool) -> dict[str, str]:
  env = p33._env_values(document)
  state = env["CANON_STATE"]
  return {
      "CANON_KV_UNIFIED": "1" if unified else "0",
      "CANON_P38_PRECHECK_ONLY": "1",
      "CANON_P38_SERVING_CAPTURE_DIR": f"{state}/p38_serving_capture",
      "CANON_P38_SERVING_CAPTURE_MAX_CALLS": str(_CAPTURE_RECORDS),
      "CANON_P38_SERVING_CAPTURE_MIN_PREFIX": str(
          _CAPTURE_PREFIX_BOUNDS[0]
      ),
      "CANON_P38_SERVING_CAPTURE_PREFIX_BOUNDS": ",".join(
          str(value) for value in _CAPTURE_PREFIX_BOUNDS
      ),
      "CANON_P38_SERVING_CAPTURE_FREE_SPACE_MULTIPLIER": "5",
      "CANON_P38_SERVING_CAPTURE_EXPECTED_PATH": "standard",
      "CANON_P38_SERVING_CAPTURE_EXPECTED_RECORDS": str(_CAPTURE_RECORDS),
      "CANON_P38_SERVING_CAPTURE_CLASSIFICATION": (
          f"{state}/p38_serving_capture.classification.json"
      ),
      "CANON_P38_SERVING_CAPTURE_ARCHIVE": f"{state}/p38_serving_capture.tar",
  }


def validate_capture_jobset(
    document: Mapping[str, Any], *, unified: bool
) -> None:
  env = p33._env_values(document)
  expected = _capture_values(document, unified=unified)
  wrong = {name: env.get(name) for name, value in expected.items() if env.get(name) != value}
  if wrong:
    raise ValueError(f"P38 serving-capture environment drifted: {wrong}")
  if not env.get("CANON_P38_MISMATCH_CAPSULE", "").endswith(".npz"):
    raise ValueError("P38 serving capture requires a mismatch capsule path")
  labels = document["metadata"].get("labels", {})
  if labels.get("canon.zero-tim/diagnostic") != "p38-serving-capture":
    raise ValueError("P38 serving-capture label is missing")
  if labels.get("canon.zero-tim/kv-unified") != ("1" if unified else "0"):
    raise ValueError("P38 KV-unified label drifted")
  if document["spec"]["failurePolicy"].get("maxRestarts") != 0:
    raise ValueError("P38 serving-capture JobSet must not restart")


def render_jobset(
    base: Mapping[str, Any], spec: Any, source_commit: str, run_id: str,
    *, unified: bool,
) -> dict[str, Any]:
  document = p33.render_jobset(base, spec, source_commit, run_id)
  main = _main_container(document)
  p33._set_named_env(
      main["env"], _capture_values(document, unified=unified), remove=()
  )
  labels = document["metadata"].setdefault("labels", {})
  labels["canon.zero-tim/diagnostic"] = "p38-serving-capture"
  labels["canon.zero-tim/kv-unified"] = "1" if unified else "0"
  p33.validate_jobset(document, spec, source_commit, run_id)
  validate_capture_jobset(document, unified=unified)
  return document


def render_all(
    *, base_path: Path, output_dir: Path, source_commit: str, run_id: str
) -> tuple[Path, ...]:
  base = p33.load_base(base_path)
  output_dir.mkdir(parents=True, exist_ok=True)
  outputs = tuple(
      output_dir / f"jobset-p38-serving-{'unified' if unified else 'stock'}.yaml"
      for _, unified in _SPECS
  )
  existing = [path for path in outputs if path.exists()]
  if existing:
    raise FileExistsError(
        "refusing to overwrite rendered P38 JobSets: "
        + ", ".join(str(path) for path in existing)
    )
  for (spec, unified), path in zip(_SPECS, outputs, strict=True):
    document = render_jobset(
        base, spec, source_commit, run_id, unified=unified
    )
    header = (
        "# Generated by canon-zero-tim/cluster/render_p38_serving_jobsets.py.\n"
        "# Do not edit this output; change the reviewed renderer instead.\n"
    )
    path.write_text(
        header + yaml.safe_dump(document, sort_keys=False), encoding="utf-8"
    )
    print(
        "[P38.SERVING.JOBSET] RENDERED "
        f"arm={'unified' if unified else 'stock'} path={path}"
    )
  return outputs


def main() -> int:
  parser = argparse.ArgumentParser()
  parser.add_argument("--source-commit", required=True)
  parser.add_argument("--run-id", required=True)
  parser.add_argument("--output-dir", required=True, type=Path)
  parser.add_argument(
      "--base",
      type=Path,
      default=Path(__file__).with_name("jobset-64chip.yaml"),
  )
  args = parser.parse_args()
  outputs = render_all(
      base_path=args.base,
      output_dir=args.output_dir,
      source_commit=args.source_commit,
      run_id=args.run_id,
  )
  print(
      "[P38.SERVING.JOBSET] VERDICT PASS "
      f"count={len(outputs)} source={args.source_commit} run_id={args.run_id}"
  )
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
