#!/bin/bash
set -e

# =====================================================
# MLPerf DeepSWE recipe: Qwen3.5-397B-A17B on TPU v7x
# =====================================================

export RCP_LOGGING="${RCP_LOGGING:-true}"
export WEIGHT_SYNC_DISABLE_TIMEOUTS="${WEIGHT_SYNC_DISABLE_TIMEOUTS:-1}"
export RAIDEN_BROADCAST_HOST_RATIO="${RAIDEN_BROADCAST_HOST_RATIO:-1.0}"
export RAIDEN_BROADCAST_PIPELINE_STAGES="${RAIDEN_BROADCAST_PIPELINE_STAGES:-4}"
export FAIL_FAST="${FAIL_FAST:-true}"
export WANDB_RESUME="${WANDB_RESUME:-allow}"
export PATHWAYS_CHECKPOINTING_IMPL="${PATHWAYS_CHECKPOINTING_IMPL:-persistence}"
export CKPT_USE_OCDBT="${CKPT_USE_OCDBT:-0}"
export CHECKPOINT_SAVE_INTERVAL_STEPS="${CHECKPOINT_SAVE_INTERVAL_STEPS:-1}"
export CHECKPOINT_ABANDON_FAILED_SAVES="${CHECKPOINT_ABANDON_FAILED_SAVES:-true}"
export CHECKPOINT_OPTIMIZER_INTERVAL_STEPS="${CHECKPOINT_OPTIMIZER_INTERVAL_STEPS:-0}"
export TUNIX_DEBUG_INFERENCE_LOGS="${TUNIX_DEBUG_INFERENCE_LOGS:-true}"
export MAX_STEPS="${MAX_STEPS:-10}"
export PYTHONFAULTHANDLER="${PYTHONFAULTHANDLER:-1}"
export ASYNC_WEIGHT_SYNC="${ASYNC_WEIGHT_SYNC:-true}"
export PIPELINE_TRAIN_MICROBATCHES="${PIPELINE_TRAIN_MICROBATCHES:-true}"
export IN_FLIGHT_WEIGHT_UPDATES="${IN_FLIGHT_WEIGHT_UPDATES:-true}"
export MAX_STALENESS="${MAX_STALENESS:-2}"
export ROLLOUT_PRIORITY_SCHEDULING="${ROLLOUT_PRIORITY_SCHEDULING:-true}"
export BATCH_SIZE="${BATCH_SIZE:-64}"
export TRAINER_FP8="${TRAINER_FP8:-true}"
export ROLLOUT_FP8="${ROLLOUT_FP8:-true}"
export ROLLOUT_REPLICAS="${ROLLOUT_REPLICAS:-128}"
export VLLM_DATA_PARALLEL_SIZE="${VLLM_DATA_PARALLEL_SIZE:-1}"
export ROLLOUT_TPU_SLICE="${ROLLOUT_TPU_SLICE:-tpu7x:2x2x1}"
export ROLLOUT_JOBSET_YAML="${ROLLOUT_JOBSET_YAML:-jobset.tpu.yaml}"

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
bash "${DIR}/mlperf_397b_1024_v7x.sh" start
