"""Parameter mapping planner types and rule helpers."""

from tunix.generate.param_mapping.spec import (
    ExecPolicy,
    MappingError,
    MappingProgram,
    MappingSpec,
    OperationRule,
    PlannedTransfer,
    RuleKey,
    Transform,
    derive_moe_source_keys,
    extract_layer_index,
    flat_key_to_path,
    normalize_rule_key,
    remove_layers_n_component,
    replace_layers_n_with_layers,
)
from tunix.generate.param_mapping.engine import (
    build_explicit_mapping_spec,
    build_transfer_plan,
    execute_transfer_plan,
    materialize_transfer_step,
    resolve_operation_target_key,
)
from tunix.generate.param_mapping.api import (
    BaseConverter,
    DirectTransferConverter,
    PreparedTransfer,
    prepare_structural_transfer,
    reshard_transfer,
    transfer_state_with_converter,
    transfer_state_directly,
    transfer_state_with_mappings,
)
from tunix.generate.param_mapping.runtime import ShapeMismatchError
from tunix.generate.param_mapping.transfer_support import (
    build_flat_dict,
    delete_target_buffers,
    fuse_moe_weights,
    reshard_in_chunks,
    snapshot_dst_sharding,
    sync_tied_lm_head_if_needed,
    unroll_scanned_layers,
)
from tunix.generate.param_mapping.structural import (
    default_structural_operation_rules,
    find_layer_component_index,
    make_structural_mapping_spec,
)

__all__ = [
    'ExecPolicy',
    'MappingError',
    'MappingProgram',
    'MappingSpec',
    'OperationRule',
    'PlannedTransfer',
    'BaseConverter',
    'DirectTransferConverter',
    'PreparedTransfer',
    'RuleKey',
    'ShapeMismatchError',
    'Transform',
    'build_explicit_mapping_spec',
    'build_flat_dict',
    'build_transfer_plan',
    'default_structural_operation_rules',
    'delete_target_buffers',
    'derive_moe_source_keys',
    'execute_transfer_plan',
    'extract_layer_index',
    'find_layer_component_index',
    'flat_key_to_path',
    'fuse_moe_weights',
    'make_structural_mapping_spec',
    'materialize_transfer_step',
    'normalize_rule_key',
    'prepare_structural_transfer',
    'reshard_transfer',
    'remove_layers_n_component',
    'replace_layers_n_with_layers',
    'reshard_in_chunks',
    'resolve_operation_target_key',
    'snapshot_dst_sharding',
    'sync_tied_lm_head_if_needed',
    'transfer_state_with_converter',
    'transfer_state_directly',
    'transfer_state_with_mappings',
    'unroll_scanned_layers',
]
