"""Exact golden renders for the production V1 full-recipe bundle."""

from __future__ import annotations

import copy
import hashlib
import importlib.util
from pathlib import Path
import tempfile
import unittest
from unittest import mock


ROOT = Path(__file__).resolve().parents[3]
SCRIPTS = (
    ROOT / "canon-zero-tim/workloads/full-recipes/scripts"
)
BASE = ROOT / "canon-zero-tim/cluster/jobset-64chip.yaml"


def _load(name: str, path: Path):
  spec = importlib.util.spec_from_file_location(name, path)
  assert spec is not None and spec.loader is not None
  module = importlib.util.module_from_spec(spec)
  spec.loader.exec_module(module)
  return module


THREE = _load("v1_full_recipe_golden_three", SCRIPTS / "render_three_full_recipes.py")
TWO = _load(
    "v1_full_recipe_golden_two",
    SCRIPTS / "render_frozenlake_full_recipes.py",
)
# Each manifest names its own generator on the first line, so the FrozenLake
# full-recipe renderer's rename is one more reviewed delta the legacy oracle
# below has to invert, exactly like the base scalars it restores by hand.
TWO_HEADER = "# Generated by v1-phase4 render_frozenlake_full_recipes.py."
TWO_LEGACY_HEADER = (
    "# Generated by v1-phase4 render_p67_frozenlake_two_full_recipes.py."
)


def _sha256(path: Path) -> str:
  return hashlib.sha256(path.read_bytes()).hexdigest()


def _env(path: Path) -> dict[str, str]:
  document = THREE.yaml.safe_load(path.read_text(encoding="utf-8"))
  return THREE._env(document)  # pylint: disable=protected-access


class V1FullRecipeGoldensTest(unittest.TestCase):

  def _render_three(self, root: Path) -> tuple[Path, ...]:
    return THREE.render_three(
        source_commit="a" * 40,
        output_dir=root,
        gsm8k_run_id="g64a",
        p45_run_id="f45a",
        m15_run_id="m15a",
        campaign_root="v1hp-a",
        base_path=BASE,
    )

  def _render_two(self, root: Path) -> tuple[Path, ...]:
    return TWO.render_two(
        source_commit="b" * 40,
        output_dir=root,
        p45_run_id="p45p67a",
        m15_run_id="m15p67a",
        campaign_root="v1p67-a",
        base_path=BASE,
    )

  def test_three_full_manifests_match_exact_goldens_twice(self):
    expected = (
        "57bb467259e1a312d14052c2a2a8cc27fdbba42e84c29be79a128588b2db2400",
        "11e29e16148ace4f64f2b926026d485e425c70af03a22b1ee3c764d1019ea6bd",
        "94d44d6b5b20de4faed74daad6ea7db387e935eac437ec861770cc5e5401bddf",
    )
    with tempfile.TemporaryDirectory() as tmp:
      first = self._render_three(Path(tmp) / "first")
      second = self._render_three(Path(tmp) / "second")
      self.assertEqual(tuple(map(_sha256, first)), expected)
      self.assertEqual(tuple(map(_sha256, second)), expected)
      for path in (*first, *second):
        self.assertNotIn("CANON_DP_REDUCE_ONCE", _env(path))
        self.assertNotIn("CANON_P32_KEEP_TAPE", _env(path))

  def test_frozenlake_two_full_manifests_match_exact_goldens_twice(self):
    expected = (
        "693f5f96e2676a0c78dc92b7b291e8c00a2b463385342e756ab3c81b0ea78078",
        "3891115d960e2b9116f2f045ff213a68176670e946cffd6d0ef4bba3afd2f732",
    )
    with tempfile.TemporaryDirectory() as tmp:
      first = self._render_two(Path(tmp) / "first")
      second = self._render_two(Path(tmp) / "second")
      self.assertEqual(tuple(map(_sha256, first)), expected)
      self.assertEqual(tuple(map(_sha256, second)), expected)
      for path in (*first, *second):
        self.assertNotIn("CANON_DP_REDUCE_ONCE", _env(path))
        self.assertNotIn("CANON_P32_KEEP_TAPE", _env(path))

  def _restore_legacy_infrastructure(self, document):
    # Invert exactly the nine scalar base changes in f712fc3b. Require the
    # reviewed new values first; do not normalize arbitrary future drift.
    queue = "kueue.x-k8s.io/queue-name"
    labels = document["metadata"]["labels"]
    self.assertEqual(labels[queue], "default")
    labels[queue] = "multislice-queue"
    jobs = document["spec"]["replicatedJobs"]
    self.assertEqual(len(jobs), 2)
    for job in jobs:
      template = job["template"]["spec"]["template"]
      self.assertEqual(template["metadata"]["labels"][queue], "default")
      template["metadata"]["labels"][queue] = "multislice-queue"
      self.assertEqual(template["spec"]["priorityClassName"], "medium")
      template["spec"]["priorityClassName"] = "very-high"
    head = jobs[0]["template"]["spec"]["template"]["spec"]
    containers = {item["name"]: item for item in head["initContainers"]}
    for name, current, previous in (
        ("pathways-proxy", {"cpu": "8", "memory": "16Gi"},
         {"cpu": "32", "memory": "200Gi"}),
        ("pathways-rm", {"cpu": "4", "memory": "16Gi"},
         {"cpu": "8", "memory": "32Gi"}),
    ):
      requests = containers[name]["resources"]["requests"]
      self.assertEqual(requests, current)
      requests.update(previous)

  def test_image_receipt_profile_defaults_and_base_are_the_only_legacy_deltas(self):
    # The TiTO provenance change added CANON_CLIENT_IMAGE to FrozenLake, and
    # the sandbox-namespace change added R2E_K8S_NAMESPACE to it.
    # Retain all old goldens as a reconstruction oracle: removing precisely
    # those independently checked receipts, restoring the stream/1 entries now
    # owned by the profile and the reviewed base fields must recover every
    # old byte hash. The original legacy hash values are not refreshed.
    legacy = {
        "three": (
            "8b4fd423073bc1b8fc39a3a4bac60d418411392018c2e1bf7df37d0062ccc341",
            "86d1f6666c2425011be5484ebbe9c8d2240685793f4f09c167ab60b10cea40ce",
            "ef25b597442d1059a62ee91b42bec969804c14c0359fe50cea7140d8e94b2b51",
        ),
        "two": (
            "c35b41922623642f920a5656d27dc04c010a31ae64599b7768376205c21a9998",
            "0e4c9fdfde5b2c3ac88116c0df3cd02370a47d1d70592033836c906687a16eea",
        ),
    }
    with tempfile.TemporaryDirectory() as tmp:
      for label, render in (("three", self._render_three), ("two", self._render_two)):
        for path, expected in zip(render(Path(tmp) / label), legacy[label], strict=True):
          raw = path.read_text(encoding="utf-8")
          document = THREE.yaml.safe_load(raw)
          self._restore_legacy_infrastructure(document)
          pod = document["spec"]["replicatedJobs"][0]["template"]["spec"]["template"]["spec"]
          main = next(item for item in pod["containers"] if item["name"] == "jax-tpu")
          receipts = [item for item in main["env"] if item["name"] == "CANON_CLIENT_IMAGE"]
          is_frozenlake = _env(path)["CANON_PROFILE_FILE"] != THREE._GSM8K_PROFILE
          self.assertEqual(receipts, [{"name": "CANON_CLIENT_IMAGE", "value": main["image"]}]
                           if is_frozenlake else [])
          namespaces = [item for item in main["env"]
                        if item["name"] == "R2E_K8S_NAMESPACE"]
          self.assertEqual(
              namespaces,
              [{"name": "R2E_K8S_NAMESPACE",
                "value": document["metadata"]["namespace"]}]
              if is_frozenlake else [],
          )
          main["env"] = [item for item in main["env"]
                         if item["name"] not in
                         ("CANON_CLIENT_IMAGE", "R2E_K8S_NAMESPACE")]
          entries = main["env"]
          for name in ("CANON_P32_KEEP_TAPE", "CANON_DP_REDUCE_ONCE"):
            self.assertTrue(all(item["name"] != name for item in entries), name)
          position = 1 + max(
              index for index, item in enumerate(entries)
              if item["name"] in ("CANON_P71_SCAN", "CANON_P67_P66_VMA_P59_ONLY")
          )
          entries[position:position] = [
              {"name": "CANON_P32_KEEP_TAPE", "value": "stream"},
              {"name": "CANON_DP_REDUCE_ONCE", "value": "1"},
          ]
          lines = raw.splitlines()[:2]
          if label == "two":
            self.assertEqual(lines[0], TWO_HEADER)
            lines[0] = TWO_LEGACY_HEADER
          header = "\n".join(lines) + "\n"
          reconstructed = header + THREE.yaml.safe_dump(document, sort_keys=False)
          self.assertEqual(hashlib.sha256(reconstructed.encode()).hexdigest(), expected)

  def test_legacy_reconstruction_rejects_unreviewed_base_values(self):
    base = THREE.yaml.safe_load(BASE.read_text(encoding="utf-8"))
    queue = "kueue.x-k8s.io/queue-name"
    paths = [("metadata", "labels", queue)]
    for index in (0, 1):
      prefix = ("spec", "replicatedJobs", index, "template", "spec", "template")
      paths.extend((prefix + ("metadata", "labels", queue),
                    prefix + ("spec", "priorityClassName")))
    for index in (0, 1):
      for resource in ("cpu", "memory"):
        paths.append(("spec", "replicatedJobs", 0, "template", "spec",
                      "template", "spec", "initContainers", index,
                      "resources", "requests", resource))
    for path in paths:
      with self.subTest(path=path):
        changed = copy.deepcopy(base)
        parent = changed
        for key in path[:-1]:
          parent = parent[key]
        parent[path[-1]] = "unreviewed"
        with self.assertRaises(AssertionError):
          self._restore_legacy_infrastructure(changed)

  def test_legacy_oracle_still_rejects_env_and_unrelated_resource_drift(self):
    render = self._render_three
    for mutation in ("training-env", "resource-limit"):
      with self.subTest(mutation=mutation):
        def changed_render(root):
          paths = render(root)
          raw = paths[0].read_text(encoding="utf-8")
          document = THREE.yaml.safe_load(raw)
          head = document["spec"]["replicatedJobs"][0]["template"]["spec"]["template"]["spec"]
          if mutation == "training-env":
            main = next(item for item in head["containers"] if item["name"] == "jax-tpu")
            next(item for item in main["env"] if item["name"] == "CANON_P71_SCAN")["value"] = "full"
          else:
            head["initContainers"][0]["resources"]["limits"]["cpu"] = "31"
          header = "\n".join(raw.splitlines()[:2]) + "\n"
          paths[0].write_text(header + THREE.yaml.safe_dump(document, sort_keys=False),
                              encoding="utf-8")
          return paths

        with mock.patch.object(self, "_render_three", side_effect=changed_render):
          with self.assertRaises(AssertionError):
            self.test_image_receipt_profile_defaults_and_base_are_the_only_legacy_deltas()


if __name__ == "__main__":
  unittest.main()
