name: Auto-assign issues
on:
  issues:
    types: 
      - [opened, reopened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/github-script@v8
        with:
          script: |
            const script = require('./\.github/workflows/issue-auto-assign.js')
            script({github, context})
